# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b8cb09e31d34d02b19ec18a6b8769baf39025ffea940eed4a2f0540c5837042785866fb164a08c978e6d50e376653f849f9c74930b198fa9ece7a35a7055cf1

test:
  secret_key_base: cd3b8a15518264cd6254494f08e4f0748bd84aabf5ace51d08c35cac9669d73ab21c65fd25404d0b7b89aca00699666134e83b300825be74ffb286b717727637

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
